// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"sse_demo/internal/app"
	"sse_demo/internal/config"
	"sse_demo/internal/http"
	"sse_demo/internal/http/controller"
	"sse_demo/internal/logging"
	"sse_demo/internal/queue/rabbitmq"
	"sse_demo/internal/service/notify"
	"sse_demo/internal/sse"
	"sse_demo/internal/store"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*app.App, error) {
	hub := sse.NewHub()
	logger, err := logging.New()
	if err != nil {
		return nil, err
	}
	notificationRepository, err := store.NewStore(cfg, logger)
	if err != nil {
		return nil, err
	}
	service := notify.NewService(notificationRepository, hub, logger)
	consumer := rabbitmq.NewConsumer(cfg, service, logger)
	publisher := rabbitmq.NewPublisher(cfg, logger)
	handler := controller.NewHandler(cfg, service, hub, logger, publisher)
	engine := http.NewRouter(handler, logger, cfg)
	appApp := app.NewApp(cfg, hub, consumer, engine, logger)
	return appApp, nil
}
