// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :execresult
INSERT INTO notifications (room, type, title, body) VALUES (?, ?, ?, ?)
`

type CreateNotificationParams struct {
	Room  string `json:"room"`
	Type  string `json:"type"`
	Title string `json:"title"`
	Body  string `json:"body"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNotification,
		arg.Room,
		arg.Type,
		arg.Title,
		arg.Body,
	)
}

const listNotificationsByRoom = `-- name: ListNotificationsByRoom :many
SELECT id, room, type, title, body, created_at
FROM notifications
WHERE room = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListNotificationsByRoomParams struct {
	Room  string `json:"room"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListNotificationsByRoom(ctx context.Context, arg ListNotificationsByRoomParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByRoom, arg.Room, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Room,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
